In [92]:
%matplotlib inline

import numpy as np # NUMPY
import pandas as pd # PANDAS
import matplotlib.pyplot as plt # MATPLOTLIB
import seaborn as sns # SEABORN
import scipy
import sklearn
import random as rd
from sklearn.decomposition import PCA
from IPython.display import display
import os 
from pathlib import Path
import shutil 


### IF WE HAVE THE CK+ DATABASE, WE CAN DO THIS CODE IN THE NEXTS CELLS TO CREATE A MINI DATABASE TO START WITH THE FEATURES

In [17]:
 os.listdir('../../ck+/Landmarks' )

['S125',
 'S133',
 'S078',
 'S117',
 'S029',
 'S035',
 'S109',
 'S079',
 'S076',
 'S099',
 'S051',
 'S156',
 'S148',
 'S506',
 'S045',
 'S077',
 'S502',
 'S052',
 'S090',
 'S014',
 'S095',
 'S104',
 'S083',
 'S130',
 'S127',
 'S059',
 'S151',
 'S136',
 'S073',
 'S085',
 'S056',
 'S069',
 'S114',
 'S138',
 'S071',
 'S137',
 'S067',
 'S110',
 'S091',
 'S503',
 'S096',
 'S070',
 'S121',
 'S046',
 'S158',
 'S139',
 'S097',
 'S010',
 'S058',
 'S037',
 'S092',
 'S102',
 'S120',
 'S504',
 'S063',
 'S106',
 'S061',
 'S066',
 'S086',
 'S107',
 'S135',
 'S055',
 'S112',
 'S501',
 'S074',
 'S131',
 'S084',
 'S101',
 'S054',
 'S072',
 'S134',
 'S126',
 'S089',
 'S999',
 'S155',
 'S119',
 'S064',
 'S129',
 'S103',
 'S124',
 'S080',
 'S075',
 'S154',
 'S062',
 'S105',
 'S113',
 'S111',
 'S082',
 'S093',
 'S087',
 'S053',
 'S088',
 'S147',
 'S034',
 'S060',
 'S065',
 'S081',
 'S042',
 'S032',
 'S108',
 'S160',
 'S005',
 'S057',
 'S115',
 'S157',
 'S022',
 'S132',
 'S116',
 'S044',
 'S149',
 'S026',
 

In [5]:
Emotion_subjects = os.listdir('../../ck+/Emotion_labels/Emotion' )
len(Emotion_subjects)
images_subjects = os.listdir('../../ck+/extended-cohn-kanade-images/cohn-kanade-images' )
len(images_subjects)
facts_subjects =  os.listdir('../../ck+/FACS_labels/FACS' )
len(facts_subjects)
landmarks_subjects =  os.listdir('../../ck+/Landmarks' )
len(landmarks_subjects)

def choose_random_subjects(main_dir, local_dir, amount):
    subjects = os.listdir(main_dir + local_dir )
    random_subjects = np.random.choice(subjects, amount,replace=False )
    return random_subjects
    
subject_number =choose_random_subjects('../../ck+/','extended-cohn-kanade-images/cohn-kanade-images', 11)



['003', '001', '002', '004']
['006', '003', '001', '005', '002', '004']
['003', '001', '005', '002', '004']
['006', '001', '002', '004']
['003', '001', '005', '002', '004']
['006', '003', '001', '005', '002', '004']
['007', '006', '003', '001', '005', '002', '004']
['001']
['006', '003', '001', '005', '002', '004']
['006']
['011', '003', '001', '005', '002', '004']


In [11]:
for number in subject_number:
  
    src = '../../ck+/extended-cohn-kanade-images/cohn-kanade-images/'  + number
    dst = '../ck+copy/extended-cohn-kanade-images/cohn-kanade-images/' + number
    destination = shutil.copytree(src, dst) 
    print(destination)

../ck+copy/extended-cohn-kanade-images/cohn-kanade-images/S064
../ck+copy/extended-cohn-kanade-images/cohn-kanade-images/S073
../ck+copy/extended-cohn-kanade-images/cohn-kanade-images/S068
../ck+copy/extended-cohn-kanade-images/cohn-kanade-images/S504
../ck+copy/extended-cohn-kanade-images/cohn-kanade-images/S014
../ck+copy/extended-cohn-kanade-images/cohn-kanade-images/S100
../ck+copy/extended-cohn-kanade-images/cohn-kanade-images/S078
../ck+copy/extended-cohn-kanade-images/cohn-kanade-images/S029
../ck+copy/extended-cohn-kanade-images/cohn-kanade-images/S022
../ck+copy/extended-cohn-kanade-images/cohn-kanade-images/S160
../ck+copy/extended-cohn-kanade-images/cohn-kanade-images/S137


In [14]:
for number in subject_number:
  
    src = '../../ck+/Emotion_labels/Emotion/'  + number
    dst = '../ck+copy/Emotion_labels/Emotion/' + number
    destination = shutil.copytree(src, dst) 
    print(destination)

../ck+copy/Emotion_labels/Emotion/S064
../ck+copy/Emotion_labels/Emotion/S073
../ck+copy/Emotion_labels/Emotion/S068
../ck+copy/Emotion_labels/Emotion/S504
../ck+copy/Emotion_labels/Emotion/S014
../ck+copy/Emotion_labels/Emotion/S100
../ck+copy/Emotion_labels/Emotion/S078
../ck+copy/Emotion_labels/Emotion/S029
../ck+copy/Emotion_labels/Emotion/S022
../ck+copy/Emotion_labels/Emotion/S160
../ck+copy/Emotion_labels/Emotion/S137


In [16]:
for number in subject_number:
  
    src ='../../ck+/FACS_labels/FACS/'  + number
    dst = '../ck+copy/FACS_labels/FACS/' + number
    destination = shutil.copytree(src, dst) 
    print(destination)

../ck+copy/FACS_labels/FACS/S064
../ck+copy/FACS_labels/FACS/S073
../ck+copy/FACS_labels/FACS/S068
../ck+copy/FACS_labels/FACS/S504
../ck+copy/FACS_labels/FACS/S014
../ck+copy/FACS_labels/FACS/S100
../ck+copy/FACS_labels/FACS/S078
../ck+copy/FACS_labels/FACS/S029
../ck+copy/FACS_labels/FACS/S022
../ck+copy/FACS_labels/FACS/S160
../ck+copy/FACS_labels/FACS/S137


In [18]:
for number in subject_number:
  
    src ='../../ck+/Landmarks/'  + number
    dst = '../ck+copy/Landmarks/' + number
    destination = shutil.copytree(src, dst) 
    print(destination)

../ck+copy/Landmarks/S064
../ck+copy/Landmarks/S073
../ck+copy/Landmarks/S068
../ck+copy/Landmarks/S504
../ck+copy/Landmarks/S014
../ck+copy/Landmarks/S100
../ck+copy/Landmarks/S078
../ck+copy/Landmarks/S029
../ck+copy/Landmarks/S022
../ck+copy/Landmarks/S160
../ck+copy/Landmarks/S137


In [127]:
subjects_landmarks = '../ck+copy/Landmarks/'
sorted_subjects =   np.sort(os.listdir('../ck+copy/Landmarks/'))  
one_subject_landmarks = '../ck+copy/Landmarks/' + 'S064/'
sorted_list = np.sort(os.listdir('../ck+copy/Landmarks/' + 'S064/')) #creo que este sort se puede quitar


    
distances_per_subject = []
for emotion in sorted_list:
    matrix_landmark_per_frame = []
    subject_landmark_emotion = one_subject_landmarks + str(emotion)    
    for i in range(0, len(os.listdir(subject_landmark_emotion))):
        data = pd.read_csv('../ck+copy/Landmarks/' + 'S064/' + str(emotion)+'/'+'S064_'+str(emotion)+'_'+ str(i+1).zfill(8)+'_landmarks.txt',  header=None)
        data.columns =['landmarks']
        quantity_of_landmarks = data.size #68
        data = data['landmarks'].str.split('   ', expand=True)
        data.columns =['landmarks', 'landmarkX', 'landmarkY']
        data =data.drop(columns=['landmarks'])
        landmarkXY=data['landmarkX'].append(data['landmarkY'], ignore_index=True)
        landmarkXY_array =landmarkXY.to_numpy(dtype=float)
        matrix_landmark_per_frame.append(landmarkXY_array)
    frame0 = matrix_landmark_per_frame[0]
    distance_landmark_per_frame = matrix_landmark_per_frame
    for i in range(0, len(distance_landmark_per_frame)):
        distance_landmark_per_frame[i] = distance_landmark_per_frame[i] - frame0
    distances_per_subject.append(distance_landmark_per_frame)


In [93]:
subjects_landmarks = '../ck+copy/Landmarks/'
sorted_subjects =   np.sort(os.listdir('../ck+copy/Landmarks/')) # we probably need to not have the sorted

distances = []
for subject in sorted_subjects:
    one_subject_landmarks = '../ck+copy/Landmarks/' + str(subject)+ '/'
    sorted_list = np.sort(os.listdir(one_subject_landmarks)) #creo que este sort se puede quitar
    distances_per_subject = []
    for emotion in sorted_list:
        matrix_landmark_per_frame = []
        subject_landmark_emotion = one_subject_landmarks + str(emotion)    
        for i in range(0, len(os.listdir(subject_landmark_emotion))):
            data = pd.read_csv('../ck+copy/Landmarks/' +  str(subject)+ '/' + str(emotion)+'/'+ str(subject)+ '_'+str(emotion)+'_'+ str(i+1).zfill(8)+'_landmarks.txt',  header=None)
            data.columns =['landmarks']
            quantity_of_landmarks = data.size #68
            data = data['landmarks'].str.split('   ', expand=True)
            data.columns =['landmarks', 'landmarkX', 'landmarkY']
            data =data.drop(columns=['landmarks'])
            landmarkXY=data['landmarkX'].append(data['landmarkY'], ignore_index=True)
            landmarkXY_array =landmarkXY.to_numpy(dtype=float)
            matrix_landmark_per_frame.append(landmarkXY_array)
        frame0 = matrix_landmark_per_frame[0]
        distance_landmark_per_frame = matrix_landmark_per_frame
        for i in range(0, len(distance_landmark_per_frame)):
            distance_landmark_per_frame[i] = distance_landmark_per_frame[i] - frame0
        distances_per_subject.append(distance_landmark_per_frame)
    distances.append(distances_per_subject)
#tenemos matrix que por cada sujeto tiene una matriz con cada emocion, que por cada distancia por emocion tiene vector con la distancia de frames con el primero por emocion

In [94]:
for i in range(0, len(distances)):
    for j in range(0, len( distances[i])):
        distances[i][j]= np.asarray( distances[i][j], dtype=object)
    distances[i]= np.asarray( distances[i], dtype=object)
distances= np.asarray( distances, dtype=object)


In [69]:
probing = distances[0]

In [70]:
 np.vstack(tuple(probing)).shape


(111, 136)

In [87]:
stacked_array = []
for i in range(0, len(distances)):
    stacked_array.append(np.vstack(tuple(distances[i])))
stacked_array= np.asarray( stacked_array, dtype=object)
total_stacked_landmarkDistance = np.vstack(tuple(stacked_array))
print(total_stacked_landmarkDistance.shape)

(965, 136)


In [89]:

my_df = pd.DataFrame(total_stacked_landmarkDistance)
my_df.to_csv('ckmock_landmark_distance.csv',header = False, index= False)

In [91]:
my_data = pd.read_csv('ckmock_landmark_distance.csv',header = None)
my_data

0        1        2        3        4        5        6        7    \
0    0.00000  0.00000  0.00000  0.00000  0.00000  0.00000  0.00000  0.00000   
1    0.00000  0.00000  0.00000  0.00000  0.00000  0.00000  0.00000  0.00000   
2    0.00000  0.00000  0.00000  0.00000  0.00000  0.00000  0.00000  0.00000   
3   -0.16370 -0.14778 -0.11964 -0.09592 -0.07529 -0.04710 -0.01633  0.03275   
4   -0.05653 -0.03715 -0.01955  0.00939  0.04707  0.07753  0.11009  0.14334   
..       ...      ...      ...      ...      ...      ...      ...      ...   
960  0.32127  0.23274  0.20477  1.21102  1.31294  1.54115  3.64450  0.61931   
961  0.29068  0.18728  0.18541  1.19783  1.28520  1.55429  3.67053  0.66286   
962  0.12751  0.04993  0.08118  1.13209  1.25521  1.57166  3.74184  0.75668   
963  0.16570  0.11675  0.11603  1.16254  1.31838  1.58746  3.74676  0.75986   
964  0.02996  0.03851  0.04223  1.11814  1.33820  1.59967  3.78032  0.82262   

         8        9    ...       126       127      128      129      130  \
0    0.00000  0.00000  ...   0.00000   0.00000  0.00000  0.00000  0.00000   
1    0.00000  0.00000  ...   0.00000   0.00000  0.00000  0.00000  0.00000   
2    0.00000  0.00000  ...   0.00000   0.00000  0.00000  0.00000  0.00000   
3    0.07564  0.11485  ...   0.09672   0.09549  0.09143  0.06910  0.06195   
4    0.18654  0.21991  ...   0.12791   0.08657  0.02855 -0.00943 -0.02158   
..       ...      ...  ...       ...       ...      ...      ...      ...   
960 -0.20548 -0.27017  ... -12.98145 -11.01479 -7.30872 -4.93901 -2.51696   
961 -0.14463 -0.18739  ... -12.69641 -10.70672 -7.03351 -4.64652 -2.27153   
962 -0.02242 -0.03719  ... -12.55571 -10.53874 -6.86940 -4.46566 -2.10693   
963 -0.02824 -0.06204  ... -12.64923 -10.67109 -6.97274 -4.60204 -2.18606   
964  0.04643  0.00811  ... -12.63352 -10.67446 -6.96772 -4.62694 -2.18836   

         131      132       133       134      135  
0    0.00000  0.00000   0.00000   0.00000  0.00000  
1    0.00000  0.00000   0.00000   0.00000  0.00000  
2    0.00000  0.00000   0.00000   0.00000  0.00000  
3    0.06268  0.07917   0.10093   0.12145  0.10884  
4   -0.01850  0.01316   0.06841   0.10249  0.07585  
..       ...      ...       ...       ...      ...  
960 -4.82460 -7.74380 -10.66298 -10.77142 -9.67844  
961 -4.50067 -7.45395 -10.40722 -10.57225 -9.42051  
962 -4.36784 -7.34376 -10.31967 -10.46400 -9.27315  
963 -4.56375 -7.48000 -10.39625 -10.44869 -9.34346  
964 -4.70047 -7.56314 -10.42581 -10.36510 -9.30850  

[965 rows x 136 columns]

In [85]:
distances[0][0][3   
]

array([-0.1636999999999773, -0.14777999999998315, -0.11964000000000397,
       -0.09591999999997824, -0.07528999999999542, -0.047100000000000364,
       -0.016329999999982192, 0.03274999999996453, 0.0756399999999644,
       0.1148499999999899, 0.15820999999999685, 0.18244999999996026,
       0.20193999999997914, 0.21401000000003023, 0.21540999999996302,
       0.20921999999995933, 0.20134999999999081, -0.13763000000000147,
       -0.10631000000000768, -0.06922000000002981, -0.04032000000000835,
       -0.014880000000005111, -0.02118999999999005, 0.011759999999981119,
       0.05518000000000711, 0.10940000000005057, 0.16388999999998077,
       0.0023600000000101318, 0.012239999999962947, 0.017400000000009186,
       0.024479999999982738, 0.01695999999998321, 0.031199999999955708,
       0.04348999999996295, 0.05729999999999791, 0.0695699999999988,
       -0.1219300000000203, -0.11511999999999034, -0.08827000000002272,
       -0.0635300000000143, -0.07997999999997774, -0.1008700000000430

In [75]:
probing[1][3]

array([-0.09793999999999414, -0.13148000000001048, 0.11354000000000042,
       -0.15156999999999243, -0.11340000000001282, -0.14485999999999422,
       0.01607000000001335, -0.3849999999999909, -0.5343799999999987,
       -0.5263500000000363, -0.44482999999996764, -0.7571799999999484,
       -0.17266999999998234, 0.16574000000002798, -0.16545999999999594,
       0.2286799999999971, 0.3847199999999589, 1.0872899999999959,
       1.1101600000000076, 0.9054199999999923, 0.7445900000000165,
       0.7454600000000369, -2.4924800000000005, -1.5837099999999964,
       -1.0489499999999907, -0.6011100000000056, -0.1320699999999988,
       -0.335140000000024, -0.48171000000002095, -0.6011299999999551,
       -0.851949999999988, -0.619259999999997, -0.36903999999998405,
       -0.052809999999965385, 0.09242999999997892, 0.1770800000000463,
       0.12547999999998183, 0.24513999999999214, 0.25621000000001004,
       0.1621099999999842, 0.0877100000000155, 0.06592000000000553,
       0.139790000000

In [34]:
distances[0][1][3   
]

array([-0.09793999999999414, -0.13148000000001048, 0.11354000000000042,
       -0.15156999999999243, -0.11340000000001282, -0.14485999999999422,
       0.01607000000001335, -0.3849999999999909, -0.5343799999999987,
       -0.5263500000000363, -0.44482999999996764, -0.7571799999999484,
       -0.17266999999998234, 0.16574000000002798, -0.16545999999999594,
       0.2286799999999971, 0.3847199999999589, 1.0872899999999959,
       1.1101600000000076, 0.9054199999999923, 0.7445900000000165,
       0.7454600000000369, -2.4924800000000005, -1.5837099999999964,
       -1.0489499999999907, -0.6011100000000056, -0.1320699999999988,
       -0.335140000000024, -0.48171000000002095, -0.6011299999999551,
       -0.851949999999988, -0.619259999999997, -0.36903999999998405,
       -0.052809999999965385, 0.09242999999997892, 0.1770800000000463,
       0.12547999999998183, 0.24513999999999214, 0.25621000000001004,
       0.1621099999999842, 0.0877100000000155, 0.06592000000000553,
       0.139790000000

In [16]:
len(distances[0][0])

29

In [130]:
# Now here we are going to try the PCA for the first feature on the mock database
#Shape Feature


#Primero vamos a tratar de leer un archivo

landmarks_example = '../ck+copy/Landmarks/' + 'S064/' + '003'
landmark_example_sorted = np.sort(os.listdir(landmarks_example ))

    
    

In [82]:
matrix_landmark_per_frame = []
for i in range(0, len(landmark_example_sorted)):
    data = pd.read_csv('../ck+copy/Landmarks/' + 'S064/' + '003/'+'S064_003_'+ str(i+1).zfill(8)+'_landmarks.txt',  header=None)
    data.columns =['landmarks']
    quantity_of_landmarks = data.size #68
    data = data['landmarks'].str.split('   ', expand=True)
    data.columns =['landmarks', 'landmarkX', 'landmarkY']
    data =data.drop(columns=['landmarks'])
    landmarkXY=data['landmarkX'].append(data['landmarkY'], ignore_index=True)
    landmarkXY_array =landmarkXY.to_numpy(dtype=float)
    matrix_landmark_per_frame.append(landmarkXY_array)


In [87]:
len(matrix_landmark_per_frame)
type(matrix_landmark_per_frame[0][0])
frame0 = matrix_landmark_per_frame[0]


In [84]:
#Acá la operacón puede ser distinta, por ahi requerimos otra metrica
distance_landmark_per_frame = matrix_landmark_per_frame


In [86]:
for i in range(0, len(distance_landmark_per_frame)):
    distance_landmark_per_frame[i] = distance_landmark_per_frame[i] - frame0


[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.

In [6]:
#Debido a que es 2l, asumo que es x e y por separado y es differencia simple y no distancia. Tratemos con la simple
   
data = pd.read_csv('../ck+copy/Landmarks/' + 'S064/' + '003/'+'S064_003_00000001_landmarks.txt',  header=None)
data.columns =['landmarks']
quantity_of_landmarks = data.size #68
data = data['landmarks'].str.split('   ', expand=True)
data.columns =['landmarks', 'landmarkX', 'landmarkY']
data =data.drop(columns=['landmarks'])
data

landmarkX      landmarkY
0   1.7176856e+02  1.8797868e+02
1   1.7474155e+02  2.2021672e+02
2   1.8119910e+02  2.5143154e+02
3   1.8578831e+02  2.8323837e+02
4   1.9599934e+02  3.1375749e+02
..            ...            ...
63  3.0847297e+02  3.0267740e+02
64  3.1850994e+02  3.0367287e+02
65  3.0855304e+02  3.0408591e+02
66  2.9890209e+02  3.0512723e+02
67  2.8657090e+02  3.0406636e+02

[68 rows x 2 columns]

In [102]:
landmarkXY=data['landmarkX'].append(data['landmarkY'], ignore_index=True)
type(landmarkXY.to_frame())

pandas.core.frame.DataFrame

In [106]:
print(landmarkXY)


0      1.7176856e+02
1      1.7474155e+02
2      1.8119910e+02
3      1.8578831e+02
4      1.9599934e+02
           ...      
131    3.0267740e+02
132    3.0367287e+02
133    3.0408591e+02
134    3.0512723e+02
135    3.0406636e+02
Length: 136, dtype: object


In [107]:
assorted_DATA = pd.DataFrame(landmarkXY)
assorted_DATA.columns =['landmarkXY']
assorted_DATA

landmarkXY
0    1.7176856e+02
1    1.7474155e+02
2    1.8119910e+02
3    1.8578831e+02
4    1.9599934e+02
..             ...
131  3.0267740e+02
132  3.0367287e+02
133  3.0408591e+02
134  3.0512723e+02
135  3.0406636e+02

[136 rows x 1 columns]

In [95]:
for i in range(0, len(distances)):
    for j in range(0, len( distances[i])):
        distances[i][j]= np.asarray( distances[i][j], dtype=object)
    distances[i]= np.asarray( distances[i], dtype=object)
distances= np.asarray( distances, dtype=object)


In [98]:
distances.shape

(5,)